copy /y NUL build/m4engine.js
type Utilities.js >> build/m4engine.js
type Pathfinding.js >> build/m4engine.js
type KeyboardModule.js >> build/m4engine.js
type Touchpad.js >> build/m4engine.js
type LActions.js >> build/m4engine.js
type M4Thing.js >> build/m4engine.js
type Text.js >> build/m4engine.js
type VerbIcon.js >> build/m4engine.js
type Dialog.js >> build/m4engine.js
type Item.js >> build/m4engine.js
type Camera.js >> build/m4engine.js
type Scene.js >> build/m4engine.js
type Character.js >> build/m4engine.js
type Options.js >> build/m4engine.js
type Inventory.js >> build/m4engine.js
type Notebook.js >> build/m4engine.js
type Actions.js >> build/m4engine.js
type Cursor.js >> build/m4engine.js
type Osd.js >> build/m4engine.js
type Core.js >> build/m4engine.js